# Generated by Django 5.0.4 on 2024-05-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='month_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
