# Generated by Django 5.0.6 on 2025-07-21 02:54

import django.db.models.deletion
import promotional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=200, verbose_name='ชื่อหมวดหมู่ (ไทย)')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อหมวดหมู่ (อังกฤษ)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบายหมวดหมู่')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
            ],
            options={
                'verbose_name': 'หมวดหมู่สื่อประชาสัมพันธ์',
                'verbose_name_plural': 'หมวดหมู่สื่อประชาสัมพันธ์',
                'ordering': ['name_th'],
            },
        ),
        migrations.CreateModel(
            name='PromotionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อรูปภาพ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบายรูปภาพ')),
                ('image', models.ImageField(upload_to=promotional.models.promotional_image_upload_to, verbose_name='รูปภาพ')),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='ข้อความทดแทน')),
                ('tags', models.CharField(blank=True, max_length=500, null=True, verbose_name='แท็ก (คั่นด้วยจุลภาค)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับการแสดง')),
                ('is_featured', models.BooleanField(default=False, verbose_name='รูปภาพเด่น')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่อัพโหลด')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='ขนาดไฟล์ (ไบต์)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='promotional.promotionalcategory', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'รูปภาพสื่อประชาสัมพันธ์',
                'verbose_name_plural': 'รูปภาพสื่อประชาสัมพันธ์',
                'ordering': ['category', 'display_order', '-created_at'],
            },
        ),
    ]
