# Generated by Django 5.0.4 on 2024-05-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_information_image10_remove_information_image7_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='time',
        ),
        migrations.AddField(
            model_name='information',
            name='date_and_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่และเวลา'),
        ),
    ]
