# Generated by Django 5.0.4 on 2024-05-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_information_time_information_date_and_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='information',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่'),
        ),
        migrations.AddField(
            model_name='information',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เวลา'),
        ),
    ]
