# Generated by Django 5.0.4 on 2024-05-24 04:53

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_information_date_and_time_information_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.image_upload_to, verbose_name='รูปภาพ 1'),
        ),
        migrations.AlterField(
            model_name='information',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.image_upload_to, verbose_name='รูปภาพ 2'),
        ),
        migrations.AlterField(
            model_name='information',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.image_upload_to, verbose_name='รูปภาพ 3'),
        ),
        migrations.AlterField(
            model_name='information',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.image_upload_to, verbose_name='รูปภาพ 4'),
        ),
        migrations.AlterField(
            model_name='information',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.image_upload_to, verbose_name='รูปภาพ 5'),
        ),
        migrations.AlterField(
            model_name='information',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.image_upload_to, verbose_name='รูปภาพ 6'),
        ),
    ]
