# Generated by Django 5.0.4 on 2024-05-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=models.TextField(blank=True, null=True, verbose_name='อธิบาย'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_issue',
            field=models.CharField(max_length=255, verbose_name='ประเด็น'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_metric',
            field=models.CharField(max_length=100, verbose_name='ตัวชี้วัด'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, verbose_name='หมวดหมู่'),
        ),
    ]
