# Generated by Django 5.0.4 on 2024-05-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categort_person',
            field=models.TextField(blank=True, null=True, verbose_name='ผู้รับผิดชอบ'),
        ),
    ]
