# Generated by Django 5.0.4 on 2024-05-25 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_category_categort_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='ชื่อหมวดหมู่')),
                ('category_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='คำอธิบายหมวดหมู่')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=255, verbose_name='ชื่อตัวชี้วัด')),
                ('indicator_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='คำอธิบายตัวชี้วัด')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_name', models.CharField(max_length=255, verbose_name='ชื่อหลักฐาน')),
                ('evidence_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='คำอธิบายหลักฐาน')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='evidences/')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='greenweb.indicator', verbose_name='ตัวชี้วัด')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=255, verbose_name='ชื่อประเด็น')),
                ('issue_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='คำอธิบายประเด็น')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='greenweb.category', verbose_name='หมวดหมู่')),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='greenweb.issue', verbose_name='ประเด็น'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to='attachments/')),
                ('attachment_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
