# Generated by Django 5.0.4 on 2024-05-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenweb', '0002_year_category_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='indicator_description',
            field=models.TextField(blank=True, null=True, verbose_name='คำอธิบายตัวชี้วัด'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_description',
            field=models.TextField(blank=True, null=True, verbose_name='คำอธิบายประเด็น'),
        ),
    ]
