# Generated by Django 5.0.4 on 2024-05-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenweb', '0003_alter_indicator_indicator_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='evidences/2024/'),
        ),
    ]
