# Generated by Django 5.0.6 on 2025-07-22 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ประเภท')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบาย')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ประเภททรัพยากร',
                'verbose_name_plural': 'ประเภททรัพยากร',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='หมวดเรื่อง')),
                ('dewey_range', models.CharField(blank=True, max_length=50, null=True, verbose_name='ช่วงเลขหมู่ดิวอี้')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบาย')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'หมวดเรื่อง',
                'verbose_name_plural': 'หมวดเรื่อง',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='ชื่อเรื่อง')),
                ('author', models.CharField(blank=True, max_length=500, null=True, verbose_name='ผู้แต่ง')),
                ('publisher', models.CharField(blank=True, max_length=300, null=True, verbose_name='สำนักพิมพ์')),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='ปีที่พิมพ์')),
                ('call_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขหมู่')),
                ('isbn', models.CharField(blank=True, max_length=17, null=True, verbose_name='ISBN')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบาย')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='จำนวนหน้า')),
                ('language', models.CharField(default='ไทย', max_length=50, verbose_name='ภาษา')),
                ('opac_url', models.URLField(blank=True, null=True, verbose_name='ลิงก์ OPAC')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='ลิงก์ภายนอก')),
                ('order_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='ลำดับ')),
                ('is_featured', models.BooleanField(default=False, verbose_name='แนะนำ')),
                ('is_available', models.BooleanField(default=True, verbose_name='มีให้บริการ')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่ม')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resourcetype', verbose_name='ประเภท')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.subject', verbose_name='หมวดเรื่อง')),
            ],
            options={
                'verbose_name': 'หนังสือ/ทรัพยากร',
                'verbose_name_plural': 'หนังสือ/ทรัพยากร',
                'ordering': ['order_number', 'title'],
                'indexes': [models.Index(fields=['resource_type'], name='resources_b_resourc_5651df_idx'), models.Index(fields=['subject'], name='resources_b_subject_e06fcc_idx'), models.Index(fields=['call_number'], name='resources_b_call_nu_4d5c69_idx'), models.Index(fields=['is_active', 'is_available'], name='resources_b_is_acti_851426_idx')],
            },
        ),
    ]
