# Generated by Django 5.0.6 on 2025-07-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audit_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ปีที่นำเข้าข้อมูล'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='รูปหน้าปก'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='ลิงก์รูปหน้าปก'),
        ),
    ]
